# Generated by Django 3.2.18 on 2023-03-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productCategory', models.CharField(max_length=255)),
                ('poductUrl', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproduct.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=3, max_digits=6)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('link', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproduct.product')),
            ],
        ),
    ]
